import { baseColors } from '../tokens';

export const darkTheme = {
  name: 'dark',
  colors: {
    text: {
      primary: baseColors.gray[50],
      secondary: baseColors.gray[300],
      muted: baseColors.gray[400],
      inverse: baseColors.gray[950],
      accent: baseColors.blue[300],
      success: baseColors.green[300],
      warning: baseColors.orange[300],
      danger: baseColors.red[300],
      label: baseColors.gray[400],
      value: baseColors.gray[50],
      technical: baseColors.gray[50],
    },
    background: {
      canvas: baseColors.gray[950],
      surface: baseColors.gray[900],
      subtle: baseColors.gray[800],
      inverse: baseColors.white,
      accent: baseColors.blue[500],
      success: baseColors.green[500],
      warning: baseColors.orange[500],
      danger: baseColors.red[500],
    },
    surface: {
      background: baseColors.gray[950],
      containerLowest: baseColors.gray[900],
      containerLow: baseColors.gray[800],
      container: baseColors.gray[700],
      containerHigh: baseColors.gray[600],
      containerHighest: baseColors.gray[500],
      dim: 'rgba(2, 6, 23, 0.22)',
    },
    border: {
      subtle: baseColors.gray[800],
      strong: baseColors.gray[700],
      accent: baseColors.blue[700],
      success: baseColors.green[700],
      warning: baseColors.orange[700],
      danger: baseColors.red[700],
      ghost: 'rgba(148, 163, 184, 0.18)',
    },
    outline: {
      variant: 'rgba(148, 163, 184, 0.34)',
      ghost: 'rgba(148, 163, 184, 0.18)',
      highContrast: baseColors.gray[50],
    },
    functional: {
      repair: baseColors.orange[400],
      inventoryAlert: baseColors.red[400],
      identifier: baseColors.gray[300],
      logistics: baseColors.blue[400],
      successInbound: baseColors.green[400],
      fulfillment: baseColors.purple[400],
      queued: baseColors.yellow[300],
    },
    status: {
      active: baseColors.green[400],
      inactive: baseColors.gray[300],
      confirmed: baseColors.blue[400],
      shipped: baseColors.purple[400],
      delivered: baseColors.green[400],
      invoiced: '#22D3EE',
      paid: baseColors.green[400],
      overdue: baseColors.red[400],
      void: baseColors.gray[300],
      draft: '#FDBA74',
      outOfStock: baseColors.red[400],
      lowStock: baseColors.yellow[400],
    },
    gradient: {
      primary: baseColors.blue[500],
      primaryDim: baseColors.blue[400],
    },
    overlay: {
      scrim: 'rgba(2, 6, 23, 0.56)',
      glass: 'rgba(15, 23, 42, 0.85)',
    },
    tonalNesting: {
      recessed: baseColors.gray[700],
      neutral: baseColors.gray[800],
      lifted: baseColors.gray[900],
    },
    focus: {
      ring: baseColors.blue[400],
      success: baseColors.green[400],
      warning: baseColors.orange[400],
      danger: baseColors.red[400],
    },
  },
  surfaces: {
    page: baseColors.gray[950],
    panel: baseColors.gray[900],
    elevated: baseColors.gray[800],
    containerLow: baseColors.gray[800],
    container: baseColors.gray[700],
    containerHigh: baseColors.gray[600],
    containerHighest: baseColors.gray[500],
  },
  gradients: {
    primaryZone: `linear-gradient(180deg, ${baseColors.blue[500]}, ${baseColors.blue[400]})`,
  },
  overlays: {
    scrim: 'rgba(2, 6, 23, 0.56)',
    glass: 'rgba(15, 23, 42, 0.85)',
  },
  signature: {
    ghostBorder: 'rgba(148, 163, 184, 0.18)',
    lineBorder: 'rgba(148, 163, 184, 0.34)',
  },
  primitives: {
    noBox: true,
    radius: 0,
  },
} as const;

export type DarkTheme = typeof darkTheme;
