/**
 * Reverse-lookup helpers for the route-permission manifest.
 *
 * The manifest at `docs/security/route-permissions.json` is generated by
 * `npm run audit-route-auth -- --emit` and committed. CI (`--check` mode)
 * verifies that the committed copy matches the live route source.
 *
 * This module wraps the manifest for runtime/UI consumption:
 *
 *   import { routesGatedBy } from '@/lib/auth/route-permission-manifest';
 *   routesGatedBy('admin.manage_staff')
 *     → [{ path: '/api/staff/route.ts', methods: ['DELETE','POST','PUT'] }, ...]
 *
 * Useful for:
 *   - the Roles admin UI's "permissions reach" column ("granting this
 *     opens N admin/inventory/etc. routes")
 *   - compliance inventories ("which permission gates this endpoint?")
 *   - the future per-permission help text in the Roles editor
 *
 * Why a JSON import rather than reading the file at runtime: Next.js
 * bundles the JSON at build time, so client components can import it
 * without a fetch. The file is tiny (~150 KB worst case).
 */

import manifestJson from '../../../docs/security/route-permissions.json';

export interface ManifestRoute {
  path: string;
  methods: string[];
  gate: string;
  permission: string | null;
  exemptReason: string | null;
}

interface Manifest {
  version: number;
  generatedAt: string;
  totalRoutes: number;
  summary: {
    permissionGated: number;
    authenticatedNoPermission: number;
    anonymousIntentional: number;
    serviceToService: number;
    ungatedRead: number;
    ungatedWrite: number;
  };
  routes: ManifestRoute[];
}

const manifest = manifestJson as Manifest;

/** Every route, keyed by path for fast lookup. */
const ROUTES_BY_PATH: ReadonlyMap<string, ManifestRoute> = (() => {
  const m = new Map<string, ManifestRoute>();
  for (const r of manifest.routes) m.set(r.path, r);
  return m;
})();

/** Permission → routes index, built once at module load. */
const ROUTES_BY_PERMISSION: ReadonlyMap<string, ReadonlyArray<ManifestRoute>> = (() => {
  const m = new Map<string, ManifestRoute[]>();
  for (const r of manifest.routes) {
    if (!r.permission) continue;
    const arr = m.get(r.permission) ?? [];
    arr.push(r);
    m.set(r.permission, arr);
  }
  return m;
})();

/**
 * Returns every route gated by the given permission. Includes routes that
 * use either `withAuth`'s `permission` option or the inline `requireRoutePerm`
 * call — both feed the same manifest.
 */
export function routesGatedBy(permission: string): ReadonlyArray<ManifestRoute> {
  return ROUTES_BY_PERMISSION.get(permission) ?? [];
}

/** Lookup the manifest entry for a specific route path (e.g. '/api/staff/route.ts'). */
export function routeByPath(path: string): ManifestRoute | null {
  return ROUTES_BY_PATH.get(path) ?? null;
}

/** Aggregate counts by gate type. Useful for a "security inventory" dashboard. */
export function permissionsWithRouteCount(): Array<{ permission: string; routeCount: number }> {
  const out: Array<{ permission: string; routeCount: number }> = [];
  for (const [permission, arr] of ROUTES_BY_PERMISSION) {
    out.push({ permission, routeCount: arr.length });
  }
  out.sort((a, b) => b.routeCount - a.routeCount);
  return out;
}

export function manifestSummary(): Manifest['summary'] {
  return manifest.summary;
}

export function manifestGeneratedAt(): string {
  return manifest.generatedAt;
}
