type TokenValue = string;

export const designTokens = {
  colors: {
    brandPrimary: '#1E6FCC',
    brandLight: '#E8F1FB',
    neutral50: '#F9FAFB',
    neutral100: '#F3F4F6',
    neutral200: '#E5E7EB',
    neutral700: '#374151',
    neutral900: '#111827',
    statusActive: '#16A34A',
    statusInactive: '#6B7280',
    statusConfirmed: '#1E6FCC',
    statusShipped: '#7C3AED',
    statusDelivered: '#16A34A',
    statusInvoiced: '#0891B2',
    statusPaid: '#16A34A',
    statusOverdue: '#DC2626',
    statusVoid: '#6B7280',
    statusDraft: '#D97706',
    statusOutOfStock: '#DC2626',
    statusLowStock: '#F59E0B',
    error: '#DC2626',
    warning: '#F59E0B',
    success: '#16A34A',
    info: '#2563EB',
  },
  typography: {
    fontSans: "'Inter', system-ui, sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    textXs: '0.75rem',
    textSm: '0.875rem',
    textBase: '1rem',
    textLg: '1.125rem',
    textXl: '1.25rem',
    text2xl: '1.5rem',
    fontNormal: '400',
    fontMedium: '500',
    fontSemibold: '600',
    fontBold: '700',
  },
  spacing: {
    space1: '0.25rem',
    space2: '0.5rem',
    space3: '0.75rem',
    space4: '1rem',
    space5: '1.25rem',
    space6: '1.5rem',
    space8: '2rem',
    space10: '2.5rem',
    space12: '3rem',
  },
} as const;

export const designTokenCssVariables: Record<string, TokenValue> = {
  '--color-brand-primary': designTokens.colors.brandPrimary,
  '--color-brand-light': designTokens.colors.brandLight,
  '--color-neutral-50': designTokens.colors.neutral50,
  '--color-neutral-100': designTokens.colors.neutral100,
  '--color-neutral-200': designTokens.colors.neutral200,
  '--color-neutral-700': designTokens.colors.neutral700,
  '--color-neutral-900': designTokens.colors.neutral900,
  '--color-status-active': designTokens.colors.statusActive,
  '--color-status-inactive': designTokens.colors.statusInactive,
  '--color-status-confirmed': designTokens.colors.statusConfirmed,
  '--color-status-shipped': designTokens.colors.statusShipped,
  '--color-status-delivered': designTokens.colors.statusDelivered,
  '--color-status-invoiced': designTokens.colors.statusInvoiced,
  '--color-status-paid': designTokens.colors.statusPaid,
  '--color-status-overdue': designTokens.colors.statusOverdue,
  '--color-status-void': designTokens.colors.statusVoid,
  '--color-status-draft': designTokens.colors.statusDraft,
  '--color-status-out-of-stock': designTokens.colors.statusOutOfStock,
  '--color-status-low-stock': designTokens.colors.statusLowStock,
  '--color-error': designTokens.colors.error,
  '--color-warning': designTokens.colors.warning,
  '--color-success': designTokens.colors.success,
  '--color-info': designTokens.colors.info,
  '--font-sans': designTokens.typography.fontSans,
  '--font-mono': designTokens.typography.fontMono,
  '--text-xs': designTokens.typography.textXs,
  '--text-sm': designTokens.typography.textSm,
  '--text-base': designTokens.typography.textBase,
  '--text-lg': designTokens.typography.textLg,
  '--text-xl': designTokens.typography.textXl,
  '--text-2xl': designTokens.typography.text2xl,
  '--font-normal': designTokens.typography.fontNormal,
  '--font-medium': designTokens.typography.fontMedium,
  '--font-semibold': designTokens.typography.fontSemibold,
  '--font-bold': designTokens.typography.fontBold,
  '--space-1': designTokens.spacing.space1,
  '--space-2': designTokens.spacing.space2,
  '--space-3': designTokens.spacing.space3,
  '--space-4': designTokens.spacing.space4,
  '--space-5': designTokens.spacing.space5,
  '--space-6': designTokens.spacing.space6,
  '--space-8': designTokens.spacing.space8,
  '--space-10': designTokens.spacing.space10,
  '--space-12': designTokens.spacing.space12,
  '--ds-color-text-primary': 'var(--color-neutral-900)',
  '--ds-color-text-secondary': 'var(--color-neutral-700)',
  '--ds-color-background-canvas': 'var(--color-neutral-50)',
  '--ds-color-background-surface': '#ffffff',
  '--ds-color-border-subtle': 'var(--color-neutral-200)',
  '--ds-font-sans': 'var(--font-sans)',
  '--ds-font-mono': 'var(--font-mono)',
};

export const designTokenStyleText = `:root {\n${Object.entries(designTokenCssVariables)
  .map(([key, value]) => `  ${key}: ${value};`)
  .join('\n')}\n}`;
