/**
 * Nango seam — server-only.
 *
 * Additive layer over the existing per-tenant credential vault. Nango runs as
 * a self-hosted auth+proxy sidecar (see docs/nango-sidecar-setup.md); this
 * module is the only place the app talks to it. Existing hand-built providers
 * never touch this file.
 *
 * Model:
 *   - Connections are created through the hosted Connect UI (OAuth dance) and
 *     keyed per-tenant. We pass `organization.id = orgId` + a stable end-user
 *     id; Nango returns a `connectionId` on success.
 *   - We persist a lightweight MARKER in `organization_integrations`
 *     (provider row, payload = { __nango, connectionId, providerConfigKey })
 *     so the admin UI shows connection state and later proxy/token calls know
 *     which Nango connection to use. The marker holds NO secret — Nango keeps
 *     the encrypted tokens in its own store and refreshes them automatically.
 *
 * If NANGO_SECRET_KEY is unset, `isNangoConfigured()` is false and every
 * caller falls back to the existing hand-built path. Nothing here activates
 * until the sidecar is wired.
 */

import 'server-only';
import { Nango } from '@nangohq/node';
import type { ProxyConfiguration } from '@nangohq/node';
import {
  getIntegrationCredentials,
  upsertIntegrationCredentials,
  deleteIntegrationCredentials,
  type IntegrationProvider,
} from './credentials';
import { nangoProviderConfigKey } from './nango-providers';
import type { OrgId } from '../tenancy/constants';

// ─── Config ─────────────────────────────────────────────────────────────────

export function isNangoConfigured(): boolean {
  return Boolean(process.env.NANGO_SECRET_KEY);
}

let _client: Nango | null = null;
function getNango(): Nango {
  if (!process.env.NANGO_SECRET_KEY) {
    throw new Error('Nango is not configured (NANGO_SECRET_KEY missing)');
  }
  if (!_client) {
    _client = new Nango({
      secretKey: process.env.NANGO_SECRET_KEY,
      // Self-host sidecar URL, e.g. http://nango-server:3003. Omit for cloud.
      ...(process.env.NANGO_HOST ? { host: process.env.NANGO_HOST } : {}),
    });
  }
  return _client;
}

/**
 * Stable end-user id we hand Nango per tenant. The actual connection id is
 * generated by Nango on connect and persisted in the marker — this is only
 * the end-user grouping key.
 */
function endUserId(orgId: OrgId): string {
  return `org_${orgId}`;
}

// ─── Connection marker (stored in organization_integrations) ────────────────

interface NangoConnectionMarker {
  __nango: true;
  connectionId: string;
  providerConfigKey: string;
}

function isMarker(value: unknown): value is NangoConnectionMarker {
  return (
    typeof value === 'object' &&
    value !== null &&
    (value as { __nango?: unknown }).__nango === true &&
    typeof (value as { connectionId?: unknown }).connectionId === 'string'
  );
}

/** Returns the persisted Nango connection for a provider, or null. */
export async function getNangoConnection(
  orgId: OrgId,
  provider: IntegrationProvider,
): Promise<{ connectionId: string; providerConfigKey: string } | null> {
  const marker = await getIntegrationCredentials<NangoConnectionMarker>(orgId, provider);
  if (!isMarker(marker)) return null;
  return { connectionId: marker.connectionId, providerConfigKey: marker.providerConfigKey };
}

/** Records (or replaces) the marker after a successful Connect UI flow. */
export async function recordNangoConnection(input: {
  orgId: OrgId;
  provider: IntegrationProvider;
  connectionId: string;
  providerConfigKey: string;
  displayLabel?: string | null;
  createdBy?: number | null;
}): Promise<void> {
  const payload: NangoConnectionMarker = {
    __nango: true,
    connectionId: input.connectionId,
    providerConfigKey: input.providerConfigKey,
  };
  await upsertIntegrationCredentials({
    orgId: input.orgId,
    provider: input.provider,
    payload,
    displayLabel: input.displayLabel ?? `Connected via Nango (${input.providerConfigKey})`,
    createdBy: input.createdBy ?? null,
  });
}

/** Removes the marker (does not revoke the connection inside Nango). */
export async function forgetNangoConnection(
  orgId: OrgId,
  provider: IntegrationProvider,
): Promise<void> {
  await deleteIntegrationCredentials(orgId, provider);
}

// ─── Connect session (mint a token for the frontend Connect UI) ─────────────

export async function createNangoConnectSession(input: {
  orgId: OrgId;
  providerConfigKey: string;
  orgName?: string | null;
}): Promise<{ token: string; expiresAt: string }> {
  const res = await getNango().createConnectSession({
    end_user: { id: endUserId(input.orgId), display_name: input.orgName ?? undefined },
    organization: { id: input.orgId, display_name: input.orgName ?? undefined },
    allowed_integrations: [input.providerConfigKey],
  });
  return { token: res.data.token, expiresAt: res.data.expires_at };
}

// ─── Calling provider APIs through Nango ────────────────────────────────────

/**
 * Returns a fresh (Nango auto-refreshed) access token for a connected
 * provider, or null if there's no connection / Nango isn't configured.
 * Use this when an existing SDK/client needs the raw bearer token.
 */
export async function getNangoAccessToken(
  orgId: OrgId,
  provider: IntegrationProvider,
): Promise<string | null> {
  if (!isNangoConfigured()) return null;
  const conn = await getNangoConnection(orgId, provider);
  if (!conn) return null;
  const token = await getNango().getToken(conn.providerConfigKey, conn.connectionId);
  // OAuth2 providers (e.g. squareup) yield a plain access-token string.
  if (typeof token === 'string') return token;
  if (token && typeof (token as { access_token?: unknown }).access_token === 'string') {
    return (token as { access_token: string }).access_token;
  }
  return null;
}

/**
 * Authenticated request through Nango's proxy — the app never handles the
 * token. Throws if the provider isn't connected or Nango isn't configured.
 */
export async function nangoProxy<T = unknown>(
  orgId: OrgId,
  provider: IntegrationProvider,
  req: Omit<ProxyConfiguration, 'providerConfigKey' | 'connectionId'>,
): Promise<T> {
  const conn = await getNangoConnection(orgId, provider);
  if (!conn) {
    throw new Error(`No Nango connection for ${provider} (org ${orgId})`);
  }
  const res = await getNango().proxy<T>({
    ...req,
    providerConfigKey: conn.providerConfigKey,
    connectionId: conn.connectionId,
  });
  return res.data;
}

/** Convenience used by the session route to resolve the catalog key. */
export { nangoProviderConfigKey };
